INSERT INTO products_categorygroup (name)
VALUES
    ('Format'),
    ('Type')
ON CONFLICT (name) DO NOTHING;

INSERT INTO products_productcategory (name, slug, description, group_id)
VALUES
    ('Bars', 'bars', 'Chocolate Bars', (SELECT id FROM products_categorygroup WHERE name = 'Format' LIMIT 1)),
    ('Chocolates', 'chocolates', 'Chocolates and Pralines', (SELECT id FROM products_categorygroup WHERE name = 'Format' LIMIT 1)),
    ('Spreads', 'spreads', 'Chocolate Spreads', (SELECT id FROM products_categorygroup WHERE name = 'Format' LIMIT 1)),
    ('Bags', 'chocolate-bags', 'Chocolate Bags', (SELECT id FROM products_categorygroup WHERE name = 'Format' LIMIT 1)),
    ('Gifts', 'gifts', 'Chocolate Gifts', (SELECT id FROM products_categorygroup WHERE name = 'Format' LIMIT 1)),
    ('Milk', 'milk-chocolate', 'Milk chocolate', (SELECT id FROM products_categorygroup WHERE name = 'Type' LIMIT 1)),
    ('Dark', 'dark-chocolate', 'Dark chocolate', (SELECT id FROM products_categorygroup WHERE name = 'Type' LIMIT 1)),
    ('White', 'white-chocolate', 'White chocolate', (SELECT id FROM products_categorygroup WHERE name = 'Type' LIMIT 1)),
    ('NO sugar', 'no-sugar-added', 'NO sugar added chocolate', (SELECT id FROM products_categorygroup WHERE name = 'Type' LIMIT 1))
ON CONFLICT (name) DO NOTHING;

INSERT INTO products_product (name, slug, description, price, discount_price, image, ingredients)
VALUES
    ('Chocoviar 75%', 'chocoviar-75',  'Intense, decisive and straight to the point: creamy dark chocolate filling in a 75% extra dark shell, covered with 75% Chocoviar crumbs.', 3, 2.5,'products_images/Chocoviar_75%.jpeg', 'CHOCOLATES WITH EXTRA DARK CHOCOLATE (18.8%) (COCOA SOLIDS: 75% MIN.) FILLING (24%) COVERED BY EXTRA DARK CHOCOLATE GRAINS (25%) (COCOA SOLIDS: 75% MIN.). GLUTEN FREE INGREDIENTS: Cocoa powder, Cocoa butter, Cocoa mass, Sugar, vegetable oils and fats (sunflower oil, cocoa butter, olive oil), Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS AND MILK'),
    ('Chocoviar Pistachio', 'chocoviar-pistachio',  'Every bite is full of surprises: this chocolate has a soft filling of whole pistachios covered in dark chocolate, garnished with toffee crumbs and nibs.', 2, NULL,'products_images/Chocoviar_Pistachio.jpeg', 'CHOCOLATES WITH PISTACHIO PASTE, ROASTED PISTACHIO AND SALT, COVERED BY CARAMEL GRAINS AND TOASTED COCOA NIBS. GLUTEN FREE INGREDIENTS: Sugar, Cocoa butter, Cocoa mass, Toasted cocoa nibs 9.0%, Aromatic caramel (sugar, glucose syrup, BUTTER (from MILK), CREAM (from MILK), water) 9.0%, PISTACHIO paste 6.9%, Piedmont HAZELNUT paste, Whole MILK powder, Roasted PISTACHIO 5.1%, WHEY powder (from MILK), Emulsifier: SOY lecithin, Salt 0.1%, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Chocoviar Crema Cacao', 'chocoviar-crema-cacao',  'Bold with a soft heart: a creamy filling of our cocoa and Piedmont Hazelnut spread in a milk chocolate shell, covered with extra dark chocolate and decorated with milk Chocoviar micro-pearls.', 2.5, NULL,'products_images/Chocoviar_Crema_Cacao.jpeg', 'CHOCOLATES FILLED WITH COCOA AND HAZELNUT SPREAD AND COVERED BY MILK CHOCOLATE GRAINS -25% (COCOA SOLIDS: 47% MIN./MILK SOLIDS: 19.5% MIN.). GLUTEN FREE INGREDIENTS: Sugar, Cocoa and HAZELNUT spread (Piedmont HAZELNUT paste 33.0%, Sugar, vegetable oils and fats (sunflower oil, cocoa butter, olive oil), Fat-reduced cocoa powder 10.0%, Skimmed MILK powder, Cocoa butter, Emulsifier: SOY lecithin, Ground vanilla beans) 19.8%, Cocoa butter, Whole MILK powder, Cocoa mass, Cocoa powder, Emulsifier: SOY lecithin, Anhydrous MILK fat, Natural vanilla flavor, Ground vanilla beans. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Chocoviar Stracciatella', 'chocoviar-stracciatella', 'A chocolate that never goes out of fashion: filled with cream, nibs and vanilla beans, milk chocolate shell and milk Chocoviar crumbs.', 2, NULL,'products_images/Chocoviar_Stracciatella.jpeg', 'CHOCOLATES FILLED -60% WITH WHITE CHOCOLATE -41.9%, VANILLA, CREAM* AND TOASTED GRAINED COCOA NIBS, COVERED WITH MILK CHOCOLATE GRAINS -25% (COCOA SOLIDS: 47% MIN., MILK SOLIDS: 19.5% MIN.). GLUTEN FREE - (*CREAM POWDER) INGREDIENTS: Sugar, Cocoa butter, Whole MILK powder, Concentrated MILK butter, Cocoa mass, Powdered CREAM (from MILK) 4.1%, WHEY powder (from MILK), Toasted cocoa nibs 1.8%, Emulsifier: SOY lecithin, Ground vanilla beans 0.3%, Anhydrous MILK fat, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('Chocoviar Arancia', 'chocoviar-arancia', 'In two bites, the refreshing aromas and bright, sunny colours of a walk in the open air: rich filling with “PGI Sicilian Blood Orange”, a dark shell and 75% Chocoviar crumbs.', 2, NULL, 'products_images/Chocoviar_Arancia.jpeg', 'CHOCOLATES WITH ORANGE FILLING -24%, COVERED BY EXTRA DARK CHOCOLATE GRAINS -25% (COCOA SOLIDS: 75% MIN.). GLUTEN FREE INGREDIENTS: Cocoa mass, Blood orange of Sicily-based preparation (Blood orange of Sicily -60%, sugar, dextrose, lemon juice concentrated, essential orange oil) 21.3%, Cocoa powder, Sugar, Cocoa butter, Vegetable fibre (chicory), Emulsifier: SOY lecithin, Acid: citric acid, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS AND MILK'),
    ('Chocoviar Crème Brulée', 'chocoviar-creme-brulee', 'Explosive and enveloping: this chocolate is filled with delicious caramel, in a dark chocolate shell, sprinkled with 75% dark chocolate microspheres.', 2.25, NULL, 'products_images/Chocoviar_Creme_Brulee.jpeg', 'PRALINE WITH SALTED CARAMEL FILLING (19%), COVERED BY EXTRA DARK CHOCOLATE GRAINS (25%) (COCOA SOLIDS: 75% MIN.). GLUTEN FREE INGREDIENTS: Cocoa mass, Sugar, Cocoa butter, Cocoa powder, Glucose syrup, Caramel (sugar, water) 6.0%, Concentrated MILK butter, Skimmed MILK powder, Condensed Sweetened whole MILK - 9% fat (MILK, sugar) 0.8%, Water, Emulsifier: SOY lecithin, Salt 0.1%, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('Pistachio Ingot 100 g', 'pistachio-ingot-100-g', 'Gourmet chocolate with pistachio paste and lightly salted white chocolate, enriched with crunchy whole pistachios. Items per pack (approx.): 8', 8.00, 6, 'products_images/Pistachio_Ingot_100_g.jpeg', 'WHITE CHOCOLATE WITH PISTACHIO PASTE, SALT AND TOASTED PISTACHIOS. GLUTEN FREE INGREDIENTS: Sugar, PISTACHIO paste 22.0%, Cocoa butter, Roasted PISTACHIO 12.0%, Whole MILK powder, WHEY powder (from MILK), Emulsifier: SOY lecithin, Salt 0.2%, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Cremino 1878 Eggs 100 g', 'cremino-1878-eggs-100-g', 'Milk Gianduia and white chocolate: the historic Cremino 1878 has been reborn to offer you a sweet Easter. Items per pack (approx.): 9', 8.50, 6.5, 'products_images/Cremino_1878_Eggs_100_g.jpeg', 'TRIPLE LAYERED CHOCOLATES WITH ALMONDS PASTE AND HAZELNUTS PASTE. GLUTEN FREE INGREDIENTS: Sugar, Cocoa butter, ALMOND paste 15.0%, Whole MILK powder, Piedmont HAZELNUT paste 13.8%, Cocoa mass, WHEY powder (from MILK), Anhydrous MILK fat, Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('NO Added Sugar filled eggs 100 g',  'no-added-sugar-filled-eggs-100-g', 'Egg with a milk chocolate shell filled with dark Gianduia cream with Piedmont Hazelnuts. With no added sugar, other than the sugar naturally present in the ingredients, and no artificial ingredients or sweeteners. Items per pack (approx.): 9',  8.50, NULL,  'products_images/NO_Added_Sugar_filled_eggs_100_g.jpeg',  'MINI EASTER EGG WITH COCOA AND MILK, WITH HAZELNUT PASTE FILLING -52%. WITH NO ADDED SUGAR. GLUTEN FREE - CONTAINS NATURALLY OCCURRING SUGARS INGREDIENTS: Vegetable fibre (chicory), Cocoa butter 26.4%, Lactose free whole MILK powder 14.7%, Cocoa mass 14.2%, Piedmont HAZELNUT paste 13.0%, Cocoa powder 1.6%, Concentrated MILK butter, Emulsifier: SOY lecithin, Natural flavouring, Ground vanilla beans. MAY CONTAIN TRACES OF OTHER NUTS.'),    ('Gift box with assorted Chocoviar chocolates 318 g', 'gift-box-assorted-chocoviar-318g', 'Precious cocoa microspheres with a powerful and sophisticated flavour, each with their own unique heart: 75% extra dark, caramel, stracciatella, orange, pistachio, Gianduia with whole PGI Piedmont Hazelnuts, and chocolate spread. Items per pack (approx.): 16', 45.90, NULL,'products_images/Gift_box_with_assorted_Chocoviar_chocolates_318_g.jpeg', 'ASSORTED CHOCOLATES. GLUTEN FREE INGREDIENTS: Sugar, Cocoa mass, Cocoa butter, Cocoa powder, Whole MILK powder, Blood orange of Sicily-based preparation (Blood orange of Sicily -60%, sugar, dextrose, lemon juice concentrated, essential orange oil), Piedmont HAZELNUT paste, Cocoa and HAZELNUT spread (Piedmont HAZELNUT paste 33.0%, Sugar, vegetable oils and fats (sunflower oil, cocoa butter, olive oil), Fat-reduced cocoa powder 10.0%, Skimmed MILK powder, Cocoa butter, Emulsifier: SOY lecithin, Ground vanilla beans), Raw sugar, Concentrated MILK butter, Toasted cocoa nibs, Aromatic caramel (sugar, glucose syrup, BUTTER (from MILK), CREAM (from MILK), water), Glucose syrup, Piedmont HAZELNUT, vegetable oils and fats (sunflower oil, cocoa butter, olive oil), PISTACHIO paste, Caramel (sugar, water), Roasted PISTACHIO, Vegetable fibre (chicory), Powdered CREAM (from MILK), WHEY powder (from MILK), Emulsifier: SOY lecithin, Skimmed MILK powder, Condensed Sweetened whole MILK - 9% fat (MILK, sugar), Water, Anhydrous MILK fat, Ground vanilla beans, Natural vanilla flavor, Salt, Acid: citric acid. CONTAINS / MAY CONTAIN TRACES OF: MILK, SOY, NUTS'),
    ('Rose, Raspberry & Almond Brutto&Buono 300 g', 'rose-raspberry-almond-brutto-buono-300-g', 'This Valentine''s collection invites you to a rendezvous unlike any other—an encounter awaited for a whole year, with none other than your beloved companion: Pixies chocolate. Crunchy almonds and raspberry nibs scattered into a rose-flavoured white chocolate heart.', 25.00, NULL,'products_images/Rose_Raspberry_&_Almond_Brutto&Buono_300_g.jpeg', 'ROSE-FLAVOURED LAYER WITH WHITE CHOCOLATE -81%, RASPBERRY GRAINS AND ROASTED GRAINED ALMONDS. GLUTEN FREE INGREDIENTS: Sugar, Cocoa butter, Chopped ALMONDS 13.0%, Whole MILK powder, WHEY powder (from MILK), Raspberry grains (glucose syrup, raspberries. 270 g of fruit per 100 g of product) 3.0%, Sunflower oil, Emulsifier: SOY lecithin, Concentrated (sweet potato, radish and cherry, apple), Natural flavouring, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Milk Hazelnut Brutto&Buono 300 g', 'milk-hazelnut-brutto-buono-300-g', 'This Valentine''s collection invites you to a rendezvous unlike any other—an encounter awaited for a whole year, with none other than your beloved companion: Pixies chocolate. Crunchy whole PGI Piedmont Hazelnuts scattered into a soft milk chocolate heart.', 25.00, NULL,'products_images/Milk_Hazelnut_Brutto&Buono_300_g.jpeg', 'MILK CHOCOLATE (COCOA SOLIDS: 31.8% MIN., MILK SOLIDS: 23.5% MIN.) WITH HAZELNUTS. GLUTEN FREE INGREDIENTS: Piedmont HAZELNUT 30.0%, Sugar, Whole MILK powder, Cocoa butter, Cocoa mass, Anhydrous MILK fat, Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Brutto & Buono Salted White Hen 160 g', 'brutto-buono-salted-white-hen-160-g', 'Add This delicious hen features crunchy whole Piedmont Hazelnuts, almonds and pistachios scattered into soft white chocolate.', 16.00, 12,'products_images/Brutto_&_Buono_Salted_White_Hen_160_g.jpeg', 'WHITE CHOCOLATE WITH SALTED ALMONDS, SALTED HAZELNUTS AND SALTED PISTACHIOS. GLUTEN FREE INGREDIENTS: Sugar, Cocoa butter, Salted ALMONDS (ALMONDS - 98.5%, salt) 11.2%, Salted Piedmont HAZELNUT (Piedmont HAZELNUT - 98.7%, salt) 11.2%, Whole MILK powder, Salted PISTACHIOS (PISTACHIOS - 98.7%, salt) 5.6%, WHEY powder (from MILK), Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Milk chocolate hen 100 g', 'milk-chocolate-hen-160-g', 'Delicious milk chocolate in the shape of a lovely hen with finely crafted details.', 13.00, NULL,'products_images/Milk_chocolate_hen_100_g.jpeg', 'MILK CHOCOLATE (COCOA SOLIDS: 31.8% MIN., MILK SOLIDS: 23.5% MIN.). GLUTEN FREE INGREDIENTS: Sugar, Whole MILK powder, Cocoa butter, Cocoa mass, Anhydrous MILK fat, Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('Milk Valentines 1 kg','milk-valentines-1kg',  'Chocolate is the language of love: share your sweet emotions with heart-shaped milk chocolates. Items per pack (approx.): 121', 63.75, 60,'products_images/Milk_Valentines_1_kg.jpeg', 'MILK CHOCOLATE (COCOA SOLIDS: 31,8% MIN., MILK SOLIDS: 23,5% MIN.). GLUTEN FREE. INGREDIENTS: Sugar, Whole MILK powder, Cocoa butter, Cocoa mass, Anhydrous MILK fat, Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('75% Extra Dark Valentines 1 kg','75-extra-dark-valentines-1kg',  'Chocolate is the language of love: share your sweet emotions with heart-shaped 75% extra dark chocolates. Items per pack (approx.): 124', 63.75, 60,'products_images/75%_Extra_Dark_Valentines_1kg.jpeg', 'EXTRA-DARK CHOCOLATE (COCOA SOLIDS: 75% MIN.). GLUTEN-FREE INGREDIENTS: Cocoa powder, Cocoa butter, Cocoa mass, Sugar, Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS AND MILK.'),
    ('Strawberry & Cream Chocomousse 1 kg', 'strawberry-cream-chocomousse-1kg', 'Crunchy strawberry chips are combined with a delicious blend of strawberry and cream to create an enveloping and creamy chocolate. Items per pack (approx.): 83', 63.75, NULL,'products_images/Strawberry_&_Cream_Chocomousse_1_kg.jpeg', 'CHOCOLATES WITH WHITE CHOCOLATE -68%, STRAWBERRY AND CREAM*. GLUTEN FREE *(CREAM POWDER) INGREDIENTS: Sugar, Cocoa butter, Whole MILK powder, Concentrated MILK butter, Strawberry crunchies (strawberry, sugar, maize starch. 3.5 kg of fresh fruit per 1 kg of product) 5.8%, Strawberry powder (strawberry, maltodextrin, acidity regulator: citric acid. 6 kg of fresh fruit per 1 kg of product) 5.2%, Powdered CREAM (from MILK) 3.7%, WHEY powder (from MILK), Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('Caramel & Vanilla Pannacotta 1 kg','caramel-vanilla-pannacotta-1kg',  'A golden drop of delicious caramel enveloped in a creamy vanilla filling, all encased in a caramel chocolate shell. Items per pack (approx.): 61', 72.25, NULL,'products_images/Caramel_&_Vanilla_Pannacotta_1_kg.jpeg', 'PRALINE WITH ‘WHITE CHOCOLATE WITH COCOA MASS AND CARAMEL’ SHELL, WITH FILLING -58% WITH LIQUID CARAMEL -8.5% AND CREAM*. GLUTEN FREE - (WHITE CHOCOLATE WITH COCOA MASS AND CARAMEL: 42%) - *(CREAM POWDER) INGREDIENTS: Sugar, Cocoa butter, Whole MILK powder, Caramel (sugar, water) 8.5%, Concentrated MILK butter, Powdered CREAM (from MILK) 3.5%, WHEY powder (from MILK), Powdered caramel (skimmed MILK powder, WHEY powder (from MILK), sugar, MILK fat, natural vanilla flavor) 1.0%, Cocoa mass 0.8%, Emulsifier: lecithin (sunflower, rapeseed), Ground vanilla beans, Emulsifier: SOY lecithin, Natural flavouring, Salt, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('Tiramisù 1 kg', 'tiramisu-1kg',  'Tiramisù, a praline with alternating layers of coffee paste, mascarpone cream and an exquisite dark chocolate finish.', 69.70, NULL,'products_images/Tiramisu_1_kg.jpeg', 'MASCARPONE FLAVOURED TRIPLE LAYERED CHOCOLATES WITH COFFEE AND DARK CHOCOLATE -33.3% (COCOA SOLIDS: 56% MIN.). GLUTEN FREE INGREDIENTS: Sugar, Cocoa butter, Cocoa mass, Concentrated MILK butter, Whole MILK powder, Coffee paste (coffee 62%, cocoa butter) 6.0%, WHEY powder (from MILK), Olive oil, Emulsifier: SOY lecithin, Natural flavouring, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('Espresso Coffee 1 kg', 'espresso-coffee-1kg', 'Espresso coffee abandons the cup to become a chocolate: seven fine blends of arabica coffee blend with intense, 75% extra dark chocolate and crunchy cocoa beans. Items per pack (approx.): 94', 72.25,NULL, 'products_images/Espresso_Coffee_1_kg.jpeg', 'DOUBLE LAYERED CHOCOLATES WITH EXTRA DARK CHOCOLATE 25% (COCOA SOLIDS: 75% MIN.), COFFEE AND TOASTED COCOA NIBS. GLUTEN FREE INGREDIENTS: Sugar, Cocoa butter, Coffee paste (coffee 62%, cocoa butter) 17.6%, Concentrated MILK butter, Cocoa mass, Cocoa powder, Whole MILK powder, Toasted cocoa nibs 4.5%, WHEY powder (from MILK), Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('Nougatine 1 kg', 'nougatine-1kg',  'The Chocolate Pixies tradition in a chocolate: crunchy caramelized PGI Piedmont hazelnut crumbs, covered with delicious 60% dark chocolate. Items per pack (approx.): 196', 63.75, NULL,'products_images/Nougatine_1_kg.jpeg', 'CARAMELIZED CHOPPED HAZELNUTS (66.2%) COVERED BY DARK CHOCOLATE (COCOA SOLIDS: 56% MIN.). GLUTEN FREE INGREDIENTS: Caramelised Piedmont HAZELNUT (sugar, Piedmont HAZELNUT 48%) 66.2%, Cocoa mass, Sugar, Cocoa powder, Cocoa butter, Glazing agent: gum arabic, Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS AND MILK.'),
    ('Cannolo 1 kg','cannolo-1kg', 'A creamy ricotta filling with candied cherries and oranges and crunchy, gluten-free biscuit crumbs, all covered in a dark chocolate shell. Items per pack (approx.): 55', 72.25, NULL,'products_images/Cannolo_1_kg.jpeg', 'PRALINE WITH DARK CHOCOLATE SHELL (COCOA SOLIDS: 56% MIN.), WITH ‘RICOTTA CHEESE’*, CANDIED ORANGE PEELS AND BISCUIT PIECES FILLING -67%. GLUTEN FREE - *(RICOTTA CHEESE POWDER) INGREDIENTS: Sugar, Cocoa butter, Cocoa mass, RICOTTA CHEESE powder (WHEY protein (from MILK), CREAM (from MILK)) 10.9%, Concentrated MILK butter, Whole MILK powder, Candied orange peels (Orange peels, glucose-fructose syrup, sucrose, dextrose, concentrated lemon juice. 145 g of orange peels per 100 g of candied product) 3.2%, Biscuit pieces (rice flour, sugar, cornstarch, cornflour, sunflower oil, vegetable fibre (bamboo), SOYA flour, emulsifier: SOYA lecithin, salt, caramelised sugar, cocoa powder, natural vanilla flavouring) 3.1%, WHEY powder (from MILK), Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS.'),
    ('60% Extra Dark Bar 70 g', '60-extra-dark-bar-70-g', 'Add 60% dark chocolate bar made from carefully selected cocoa mass with a sweet and seductive flavour, dominated by floral, fruity and syrupy notes.', 5, NULL,'products_images/60%_Extra_Dark_Bar-70_g.jpeg', 'DARK CHOCOLATE (COCOA SOLIDS: 60% MIN.). GLUTEN FREE INGREDIENTS: Cocoa mass, Sugar, Cocoa butter, Emulsifier: SOY lecithin. MAY CONTAIN TRACES OF NUTS AND MILK'),
    ('75% Extra Dark Bar 78 g', '75-extra-dark-bar-78-g', 'This intense and persistent 75% extra dark chocolate bar releases enveloping notes of cocoa, reminiscent of hot chocolate.', 6, NULL,'products_images/60%_Extra_Dark_Bar-70_g.jpeg', 'EXTRA DARK CHOCOLATE (COCOA SOLIDS: 75% MIN.). GLUTEN FREE INGREDIENTS: Cocoa powder, Cocoa butter, Cocoa mass, Sugar, Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF NUTS AND MILK'),
    ('White Chocolate with Salted Nuts bar 100 g', 'white-chocolate-with-salted-nuts-bar-100-g', 'A white chocolate bar with hazelnuts, almonds and lightly-salted pistachios.', 7.5, 6,'products_images/White_Chocolate_with_Salted_Nuts_bar_100_g.jpeg', 'WHITE CHOCOLATE WITH SALTED ALMONDS -10%, SALTED HAZELNUTS -10% AND SALTED PISTACHIOS -5%. GLUTEN FREE INGREDIENTS: Sugar, Cocoa butter, Whole MILK powder, Salted ALMONDS (ALMONDS - 98.5%, salt) 10.0%, Salted Piedmont HAZELNUT (Piedmont HAZELNUT - 98.7%, salt) 10.0%, Salted PISTACHIOS (PISTACHIOS - 98.7%, salt) 5.0%, WHEY powder (from MILK), Emulsifier: SOY lecithin, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Cremino Caramel Gold Bar 100 g', 'cremino-caramel-gold-bar-100-g', 'Dedicated to caramel lovers, an ambrosial embrace between a layer of dark chocolate with almond paste and creamy white chocolate with caramel. Expiry date: less than 3 months', 7.5, 6.5,'products_images/Cremino_Caramel_Gold_Bar_100_g.jpeg', 'TRIPLE LAYER OF DARK CHOCOLATE -25% (COCOA SOLIDS: 56% MIN.) WITH ALMOND PASTE AND WHITE CHOCOLATE WITH COCOA MASS AND CARAMEL WITH ALMOND PASTE. GLUTEN FREE – (WHITE CHOCOLATE WITH COCOA MASS AND CARAMEL: 50%) INGREDIENTS: Sugar, ALMOND paste 25.0%, Cocoa butter, Cocoa mass 12.1%, Whole MILK powder, Powdered caramel (skimmed MILK powder, WHEY powder (from MILK), sugar, MILK fat, natural vanilla flavor) 1.2%, Emulsifier: lecithin (sunflower, rapeseed), Natural flavouring, Emulsifier: SOY lecithin, Salt, Natural vanilla flavor. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('NO Added Sugar Milk Hazelnut Bar 100 g', 'no-added-sugar-milk-hazelnut-bar-100-g', 'The winning combination of cocoa and milk, with a sweet, vanilla flavour and whole PGI Piedmont Hazelnut from a short supply chain. No artificial sweeteners and no added sugars other than those naturally present in selected quality ingredients.', 8.2, NULL,'products_images/NO_Added_Sugar_Milk_Hazelnut_Bar_100_g.jpeg', 'BAR WITH COCOA, MILK AND HAZELNUTS. WITH NO ADDED SUGAR. GLUTEN FREE - CONTAINS NATURALLY OCCURRING SUGARS INGREDIENTS: Vegetable fibre (chicory), Piedmont HAZELNUT 25.0%, Cocoa butter 23.8%, Lactose free whole MILK powder 14.7%, Cocoa mass 9.4%, Concentrated MILK butter, Emulsifier: SOY lecithin, Natural flavouring, Ground vanilla beans. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Milk and hazelnut spread 450 g', 'milk-hazelnut-spread-450-g', 'Spread with 45% PGI Piedmont Hazelnuts and milk chocolate. Creamy goodness, genuine and free of artificial flavourings.', 22, NULL,'products_images/Milk_and_hazelnut_spread_450_g.jpeg', 'HAZELNUT AND COCOA SPREAD. GLUTEN FREE INGREDIENTS: Piedmont HAZELNUT paste 45.0%, Sugar, Fat-reduced cocoa powder 9.0%, Skimmed MILK powder 5.0%, Cocoa butter, Emulsifier: SOY lecithin. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('NO Added Sugar hazelnut spread 200 g', 'no-added-sugar-hazelnut-spread-200-g', 'The iconic spread with PGI Piedmont Hazelnut, in a version with no artificial sweeteners and no added sugars other than those naturally present in the selected quality ingredients.', 8, NULL,'products_images/NO_Added_Sugar_hazelnut_spread_200_g.jpeg', 'HAZELNUT AND COCOA SPREAD. WITH NO ADDED SUGARS. GLUTEN FREE - CONTAINS NATURALLY OCCURRING SUGARS INGREDIENTS: Vegetable fibre (chicory), Piedmont HAZELNUT paste 28.1%, vegetable oils and fats (sunflower oil, cocoa butter, olive oil), Fat-reduced cocoa powder 9.3%, Lactose free whole MILK powder, Emulsifier: SOY lecithin, Natural flavouring, Ground vanilla beans. MAY CONTAIN TRACES OF OTHER NUTS.'),
    ('Milk and hazelnut spread 200 g', 'milk-hazelnut-spread-200-g', 'Spread with 45% PGI Piedmont Hazelnuts and milk chocolate. Creamy goodness, genuine and free of artificial flavourings.', 15, 12.75,'products_images/Milk_and_hazelnut_spread_200_g.jpeg', 'HAZELNUT AND COCOA SPREAD. GLUTEN FREE INGREDIENTS: Piedmont HAZELNUT paste 45.0%, Sugar, Fat-reduced cocoa powder 9.0%, Skimmed MILK powder 5.0%, Cocoa butter, Emulsifier: SOY lecithin. MAY CONTAIN TRACES OF OTHER NUTS.')
ON CONFLICT (slug) DO NOTHING;

WITH products AS (
    SELECT id, slug FROM products_product
),
categories AS (
    SELECT id, slug FROM products_productcategory
),
product_category_map (product_slug, category_slugs) AS (
    VALUES
        ('chocoviar-75', ARRAY['chocolates', 'dark-chocolate']),
        ('chocoviar-pistachio', ARRAY['chocolates', 'dark-chocolate']),
        ('chocoviar-crema-cacao', ARRAY['chocolates', 'milk-chocolate']),
        ('chocoviar-stracciatella', ARRAY['chocolates', 'milk-chocolate']),
        ('chocoviar-arancia', ARRAY['chocolates', 'dark-chocolate']),
        ('chocoviar-creme-brule', ARRAY['chocolates', 'dark-chocolate']),
        ('pistachio-ingot-100-g', ARRAY['chocolates', 'white-chocolate']),
        ('cremino-1878-eggs-100-g', ARRAY['chocolates', 'white-chocolate', 'milk-chocolate']),
        ('no-added-sugar-filled-eggs-100-g', ARRAY['chocolates', 'milk-chocolate', 'no-sugar-added']),
        ('gift-box-assorted-chocoviar-318g', ARRAY['gifts', 'dark-chocolate', 'milk-chocolate']),
        ('rose-raspberry-almond-brutto-buono-300-g', ARRAY['gifts', 'white-chocolate']),
        ('milk-hazelnut-brutto-buono-300-g', ARRAY['gifts', 'milk-chocolate']),
        ('brutto-buono-salted-white-hen-160-g', ARRAY['gifts', 'white-chocolate']),
        ('milk-chocolate-hen-160-g', ARRAY['gifts', 'milk-chocolate']),
        ('milk-valentines-1kg', ARRAY['chocolate-bags', 'milk-chocolate']),
        ('75-extra-dark-valentines-1kg', ARRAY['chocolate-bags', 'dark-chocolate']),
        ('strawberry-cream-chocomousse-1kg', ARRAY['chocolate-bags', 'white-chocolate']),
        ('caramel-vanilla-pannacotta-1kg', ARRAY['chocolate-bags', 'milk-chocolate']),
        ('tiramisu-1kg', ARRAY['chocolate-bags', 'dark-chocolate']),
        ('espresso-coffee-1kg', ARRAY['chocolate-bags', 'dark-chocolate']),
        ('nougatine-1kg', ARRAY['chocolate-bags', 'dark-chocolate']),
        ('cannolo-1kg', ARRAY['chocolate-bagss', 'dark-chocolate']),
        ('60-extra-dark-bar-70-g', ARRAY['bars', 'dark-chocolate']),
        ('75-extra-dark-bar-78-g', ARRAY['bars', 'dark-chocolate']),
        ('white-chocolate-with-salted-nuts-bar-100-g', ARRAY['bars', 'white-chocolate']),
        ('cremino-caramel-gold-bar-100-g', ARRAY['bars', 'white-chocolate', 'dark-chocolate']),
        ('no-added-sugar-milk-hazelnut-bar-100-g', ARRAY['bars', 'milk-chocolate', 'no-sugar-added']),
        ('milk-hazelnut-spread-450-g', ARRAY['spreads', 'milk-chocolate']),
        ('no-added-sugar-hazelnut-spread-200-g', ARRAY['spreads', 'milk-chocolate', 'no-sugar-added']),
        ('milk-hazelnut-spread-200-g', ARRAY['spreads', 'milk-chocolate'])
)
INSERT INTO products_product_categories (product_id, productcategory_id)
SELECT p.id, c.id
FROM product_category_map pcm
JOIN products p ON pcm.product_slug = p.slug
JOIN categories c ON c.slug = ANY(pcm.category_slugs)
ON CONFLICT (product_id, productcategory_id) DO NOTHING;










