# Generated by Django 5.1.6 on 2025-03-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
