# Generated by Django 5.1.6 on 2025-02-23 09:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='basket_history',
            field=models.JSONField(default=list, verbose_name='Basket history'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=64, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', verbose_name='Phone number'),
        ),
    ]
