# Generated by Django 5.1.6 on 2025-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
